---
title: "Product Range Analysis"
author: "Mark Culp"
date: "April 27, 2018"
output: html_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)

# Load libraries
library(dplyr)
library(readxl)
library(ggplot2)

```


```{r loadDS, echo=FALSE}

# ----------------------------------
# Product Range Performance (prp)
# ----------------------------------

# Read in 'Product Range Performance worksheet
prp <- read_xlsx("Product-Range-Management.xlsx", sheet = "Basic Option", skip = 2)

# Create valid column names for 'Product Range 
# Performance' table
h1 <- colnames(prp) %>%
  make.names()
names(prp) <- gsub("\\.\\.","\\.",h1)
rm(h1)
prp <- rename(prp, Category = X__1)

```

#### Category Space Management

```{r rangeAnyl, echo=FALSE}

# ----------------------------------
# Category Space (catSpace) from
# Product-Range-Management.xlsx
# ----------------------------------

# Get category space in square meters
catSpace <- prp[1:6,1:2] %>%
  rename(Space = Space.In.sq.m)

# Plot category space totals
ggplot(catSpace, aes(x = Category, y = Space )) +
  geom_bar(stat = "identity") +
  ggtitle("Category Space Totals \n (all stores, square meters)")

# ----------------------------------
# Sales by Category (salesByCat) from
# Product-Range-Management.xlsx
# ----------------------------------

# Get sales by category 
#  (USD in thousands)
salesByCat <- prp[1:6,c(1,3)] %>%
  rename(Sales = Sales.generated.In.thousands.of.USD)

# Plot sales totals by category
ggplot(salesByCat, aes(x = Category, y = Sales )) +
  geom_bar(stat = "identity") +
  ggtitle("Sales by Category \n (all stores, USD in thousands)")

# ----------------------------------
# Sales Density (salesDens) 
# by product category 
# from Product-Range-Management.xlsx
# ----------------------------------

# Calculate sales density by category
salesDens <- salesByCat[,2] / catSpace[,2] * 1000
salesDens <-  cbind(salesByCat[,1], salesDens[,1]) %>%
  rename(Sales_Density = 'salesDens[, 1]')
  
# Plot sales density by category
ggplot(salesDens, aes(x = Category, y = Sales_Density )) +
  geom_bar(stat = "identity") +
  ggtitle("Sales Density by Category \n    (USD per sq meter)")

# ----------------------------------
# Sales Margin (margins) 
# by product category 
# from Product-Range-Management.xlsx
# ----------------------------------

# Get margin breakdown by category
margins <- prp[1:6,c(1,5)] %>%
  rename(Margins = X.Margin)

# Plot margins by category
ggplot(margins, aes(x = Category, y = Margins )) +
  geom_bar(stat = "identity") +
  ggtitle("Margins by Category \n      (percent)")


# ----------------------------------
# Margin Density (marginDens) 
# by product category 
# from Product-Range-Management.xlsx
# ----------------------------------

# Calculate margin density by product category 
marginDens <- salesDens[,2] * margins[,2] %>%
  rename(Margin_Density = Margins)

# Reformat as a tibble w 2 cols
marginDens <- as_tibble(cbind(salesDens[,1], marginDens[,1])) %>%
  rename(Category = V1, Margin_Density = V2)

# Plot margin density by category
ggplot(marginDens, aes(x = Category, y = Margin_Density )) +
  geom_bar(stat = "identity") +
  ggtitle("Margin Density by Category \n    (USD per sq meter)")


```

### Appendix

#### Load libraries

```{r setup2, ref.label='setup', eval=FALSE}
```

#### Load datasets/worksheets

```{r loadDS2, ref.label='loadDS', eval = FALSE}
```








